snowflake_tpch:
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: dbt_role
      warehouse: dbt_wh
      database: dbt_db
      schema: >
        {% set deployment = env_var('DAGSTER_CLOUD_DEPLOYMENT_NAME', 'main') %}
        {% if deployment == 'main' %}
          dbt_schema
        {% else %}
          s_{{ deployment
              | lower
              | replace('-', '_')
              | replace('/', '_') }}
        {% endif %}
      threads: 5
  target: dev
